# Generated by Django 5.2.14 on 2026-05-10 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_type', models.CharField(choices=[('official', 'Oficial'), ('pre_technical', 'Pre-tecnica')], default='official', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('documents_validated', 'Documentos validados'), ('pre_evaluated', 'Pre-evaluacion completada'), ('visual_review', 'Inspeccion visual'), ('mechanical_test', 'Pruebas tecnicas'), ('results_recorded', 'Resultados registrados'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('certified', 'Certificado emitido')], default='pending', max_length=30)),
                ('overall_result', models.CharField(blank=True, max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('documents_validated_at', models.DateTimeField(blank=True, null=True)),
                ('pre_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('visual_review_at', models.DateTimeField(blank=True, null=True)),
                ('mechanical_test_at', models.DateTimeField(blank=True, null=True)),
                ('results_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_record', to='scheduling.appointment')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='inspection_photos/')),
                ('label', models.CharField(max_length=120)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspectionrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=80)),
                ('item_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pass', 'Cumple'), ('fail', 'No cumple'), ('na', 'No aplica')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='inspections.inspectionrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=40, unique=True)),
                ('file', models.FileField(upload_to='certificates/')),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='inspections.inspectionrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=80)),
                ('result', models.CharField(choices=[('valid', 'Valido'), ('invalid', 'Invalido'), ('na', 'No aplica')], default='valid', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_checks', to='inspections.inspectionrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TirePressureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spare_tire_1', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('spare_tire_2', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('no_spare_tire', models.BooleanField(default=False)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tire_pressure', to='inspections.inspectionrecord')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreEvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_key', models.CharField(choices=[('soat_vigente', 'SOAT vigente'), ('licencia_transito', 'Presento licencia de transito'), ('identificacion', 'Presento identificacion'), ('vehiculo_limpio', 'Vehiculo limpio'), ('vehiculo_vacio', 'Vehiculo vacio'), ('dispositivos_seguridad', 'Dispositivos de seguridad deshabilitados'), ('sin_tapacubos', 'Inexistencia de tapacubos'), ('preparado_inspeccion', 'Vehiculo preparado para la inspeccion')], max_length=40)),
                ('result', models.CharField(choices=[('yes', 'Si'), ('no', 'No'), ('na', 'No aplica')], max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_evaluation_items', to='inspections.inspectionrecord')),
            ],
            options={
                'unique_together': {('inspection', 'item_key')},
            },
        ),
        migrations.CreateModel(
            name='AxleTirePressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('axle_number', models.PositiveSmallIntegerField()),
                ('is_double_tire', models.BooleanField(default=False)),
                ('single_pressure', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('left_outer', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('left_inner', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('right_outer', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('right_inner', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axles', to='inspections.tirepressurerecord')),
            ],
            options={
                'ordering': ['axle_number'],
                'unique_together': {('record', 'axle_number')},
            },
        ),
    ]
