# Generated by Django 5.2.14 on 2026-05-10 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plate', models.CharField(max_length=10, unique=True)),
                ('vehicle_type', models.CharField(choices=[('light', 'Liviano'), ('heavy', 'Pesado'), ('motorcycle', 'Motocicleta')], max_length=20)),
                ('vehicle_class', models.CharField(blank=True, choices=[('auto', 'Automovil'), ('pickup', 'Camioneta'), ('suv', 'Campero'), ('van', 'Microbus / Van'), ('truck', 'Camion'), ('bus', 'Bus'), ('motorcycle', 'Motocicleta'), ('other', 'Otro')], max_length=20)),
                ('service_category', models.CharField(choices=[('particular', 'Particular'), ('commercial', 'Comercial'), ('public', 'Publico')], default='particular', max_length=20)),
                ('brand', models.CharField(max_length=80)),
                ('model_line', models.CharField(max_length=120)),
                ('model_year', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=40)),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasolina'), ('diesel', 'Diesel'), ('hybrid', 'Hibrido'), ('electric', 'Electrico'), ('gas', 'Gas')], max_length=20)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('num_axes', models.PositiveSmallIntegerField(default=2)),
                ('num_passengers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('displacement', models.PositiveIntegerField(blank=True, help_text='Cilindraje en cc', null=True)),
                ('tinted_windows', models.BooleanField(default=False)),
                ('armored', models.BooleanField(default=False)),
                ('non_functional', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
