# Generated by Django 5.2.14 on 2026-05-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registration_city',
            field=models.CharField(blank=True, help_text='Ciudad de matrícula del vehículo', max_length=120),
        ),
    ]
