# Generated by Django 5.2.14 on 2026-05-10 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('source', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('related_entity', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_time', models.DateTimeField()),
                ('queue_position', models.PositiveIntegerField(default=0)),
                ('inspection_type', models.CharField(choices=[('official', 'Oficial'), ('pre_technical', 'Pre-tecnica')], default='official', max_length=20)),
                ('foreign_vehicle', models.BooleanField(default=False)),
                ('plate_confirmed', models.BooleanField(default=False)),
                ('customer_confirmed', models.BooleanField(default=False)),
                ('documents_complete', models.BooleanField(default=False)),
                ('objects_in_vehicle', models.BooleanField(default=False)),
                ('driver_is_owner', models.BooleanField(default=True)),
                ('driver_name', models.CharField(blank=True, max_length=80)),
                ('driver_first_surname', models.CharField(blank=True, max_length=80)),
                ('driver_second_surname', models.CharField(blank=True, max_length=80)),
                ('driver_id_type', models.CharField(choices=[('cc', 'Cedula de ciudadania'), ('ce', 'Cedula de extranjeria'), ('passport', 'Pasaporte'), ('nit', 'NIT'), ('ti', 'Tarjeta de identidad')], default='cc', max_length=20)),
                ('driver_id_number', models.CharField(blank=True, max_length=32)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('driver_email', models.EmailField(blank=True, max_length=254)),
                ('driver_address', models.CharField(blank=True, max_length=255)),
                ('driver_city', models.CharField(blank=True, max_length=120)),
                ('driver_license_category', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], max_length=5)),
                ('driver_hearing_impaired', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='scheduling.appointment')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
