# Generated by Django 5.2.14 on 2026-05-17 18:51

import apps.operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclereception',
            name='damage_annotations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vehiclereception',
            name='inspection_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclereception',
            name='inspection_subtype',
            field=models.CharField(choices=[('primera', 'Primera inspeccion'), ('reinspeccion', 'Re-inspeccion')], default='primera', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclereception',
            name='inventory',
            field=models.JSONField(blank=True, default=apps.operations.models._default_inventory),
        ),
        migrations.AddField(
            model_name='vehiclereception',
            name='signature_client',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiclereception',
            name='signature_officer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehiclereception',
            name='inspection_type',
            field=models.CharField(choices=[('official', 'Oficial'), ('pre_technical', 'Pre-tecnica'), ('preventiva', 'Preventiva')], default='official', max_length=20),
        ),
    ]
